* Note-taking, todo lists, Papers, and Read-it-Later
I've struggled to find productivity tools that I've liked for as long as I've been using computers.
Recently I took the plunge and started trying to learn org-mode.

org-mode is great; there's plenty written about how great it is so I'm going to skip that part.

In theory, org-mode could replace a large number of the tools I use including:
- My calendar
- [[https://todoist.com/][todoist]] todo list app
- [[https://www.mendeley.com][Mendeley]] to manage papers and keep track of what I've read
- A random pile of markdown files in a git repo to track thoughts
- Randomly assorted notes that I've emailed to myself

In theory, I could take all of this, capture it in one place, and have a coherant, organized, searchable record of all of the things.
As it stands, I've mostly kept notes to myself in a very disjoint manner, and I keep losing track of important references, important articles, etc.

I've struggled with this for a long time because I am very unwilling to yield on user experience.
If I'm typing large amounts of text, it must be in a powerful text editor.
Dark mode is a requirement for anything I'm going to spend any amount of time looking at.
Plain text is a hard requirement, ideally in a format that [[https://pandoc.org/][pandoc]] can manipulate.
Finally, a CLI interface is pretty crucial for me.
I very much desire the ability integrate with other powerful CLI tools (git, grep, awk, sed, find, curl).

I care about the last point the most; Integration with other tools is critical.
I spend tons of time piping text through [[https://github.com/junegunn/fzf][fzf]] (and more recently [[https://github.com/emacs-helm/helm][helm]] in emacs).
I want to manipulate my TODO list with =grep= and =awk=.
I want to search for notes with =grep= and [[https://github.com/BurntSushi/ripgrep][ripgrep]].
If I make a spreadsheet of some sort, I want to be able to drop into python trivially and manipulate this as a numpy array.

I can't say for sure that any of this is actually _useful_, but, philosophically, I feel like I should be able to do all of these things.

If you are reading this and comparing it to the list I gave above, you might notice that none of the tools above meet those requirements.
Because I'm so picky, I just keep not deciding what I like and I'm stuck with junk.

When I started trying out org-mode, I thought this would be my future, until, I tried to edit my org-mode files from a mobile device.

There are a number of quite good apps for editing org files a mobile device.
With [[https://nextcloud.com/][nextcloud]], I was even able to get syncing back to my NAS working.

I didn't really find any of these experiences to be quite right, for lack of a better word.
It just didn't feel like I was using the same org-mode that I had been using inside of emacs, and, the apps, despite being wonderful, are not as polished as the other purpose-built apps I'm already using.

I think there's something to this; The things I like about org-mode fly completely in the face of moden mobile app (and web app, and other apps) design.

I like org-mode because I like plain-text, fancy key bindings, a common interface for everything, the ability to script easily, and the ability to shell out to other tools.
Keybindings and plain-text are awkward on a mobile app.
Scripting and first class, *simple*, integrations with other tools seem to be practically non-existent outside of tools used by developer, and, [[https://discourse.ardour.org/t/is-open-source-a-diversion-from-what-users-really-want/102665][as observed by Paul Davis]], massive commercial software packages.

I'm not sure why consumer-focused modern apps are so much less "unixy" than what I'm looking for.

Part of me wants to speculate that it is because very few of the modern UX designers have spent time in an environment where they can use =grep= to search everything (instead of using some differently-broken app/site specific search box for every app/site you use).

Another part of me wonders if maybe I'm just wrong; maybe the new way is better.
Maybe the modern apps are actually way easier to use, maybe using HTTP APIs and writing code in high level languages to glue stuff together is a better way to integrate things than jamming text together.
Maybe hard to use CLI interfaces for my TODO list are just a burning mental cycles that would be better spent on real, productive work.

Finally, maybe this is just because the "old stuff" is stable and mature.
Integrations for everything are already built.
For example, I can read my IMAP email from basically anywhere.
This isn't because IMAP is better or easier that the todoist API, it has just been around longer and has been widely adopted

For now, I'm going to stop trying to make my phone into a unix machine.

Instead, I'm focusing on using my phone to:
- Quickly capture new tasks, quick notes, important documents, etc on my phone
  - Once captured, I can wait until I get to a real computer to read, sort, annotate, etc
- Get a convinient read-only, searchable view into my notes and documents

Once I had this realization, it became clear to me why the apps I've been using are the apps that I've stuck with:
- Email with integrated calendar
  - I can quickly capture events that are sent to me
  - I have nice read only access to the calendar from mobile apps
  - I never send invites from my phone, I almost always use a real computer for this
- [[https://todoist.com/][todoist]] todo list app
  - Fantastic capture experience on mobile and in a web browser
  - The quick "today" and "next 7 days" view are great
- [[https://www.mendeley.com][Mendeley]] to manage papers and keep track of what I've read
  - Decent capture experience in a web browser
  - Decent capture experience in the mobile apps
  - I never read or annotate papers on my phone
- Randomly assorted notes that I've emailed to myself
  - Great capture experience, can capture from literally anywhere

Now that I've realized what I'm doing, I'm trying to be much more careful to bring my notes into org-mode, both at home, and at the office.
I haven't figured out my read-only, searchable org-mode view, but reading org-mode on mobile is a much easier problem than writing org-mode.
