#+PROPERTY: header-args :eval never-export

#+BEGIN_EXAMPLE
** Day 9
This problem asks you to first try and make the largest possible rectangle from a set of points.
I made a short false start trying to sort by magnitude of the points, then take min/max of the sorted list.
This doesn't work.
I switched to brute forcing it, which worked, but was a bit of a letdown.
I'm still not sure if there's a better way to do this.

Part 2 was much harder. Now we had to find the largest rectangles that fit inside of a region.

With a bit of help from the internet, I figured out this approach:
1. compress the coordinates to shrink the size of the structures
2. flood-fill to find the contiguous region
3. compute a prefix-sum down the x direction, treating "in region" as 1, and "out of region" as zero
4. make a list of all possible rectangles, and check if they are valid rectangels using the prefix sum we previously computed
5. find the largest by area from the valid list

Here's a visual example in ascii art from my solution:
#+begin_src elisp
;; pick a pair of red points [] and check if they make a rectangle
;;
;;    0    0    0    0    0    0 
;;    0    0   (1)   2   (3)   3
;;    0   [1]  (2)   3    4    4
;;    0   (1)   2   (3)   4    4
;;    0    0    0   (1)  [2]   2
;;    0    0    0    0    0    0
;;
;; To check if (ax,ay) and (bx,by) is a valid rectangle, just have to work down
;; the y direction and check that the prefix sum indicates if the full region
;; was filled.
;;
;; for y from ay to by:
;;   vec[bx] = vec[ax] + (bx-ax)
#+end_src

Traditionally I would have stayed away from this style of problem because all of the coordinate indexing is fiddly.
But, since I had set the goal to finish, I actually had to do it.

I was pleasantly suprised at how much fun the problem was, especially since I could get AI to fix all the fiddly coordinate bugs.
The flood-fill was fun to write, and the coordinate compression trick to speed it all up was nice too.

In the end, I'm still not happy with the performance of my code; the solution takes about 1 second to run.
This is a problem that rewarded using correct structures and algorithms.

** Day 10
Day 10 is a fantastic problem.
Part 1 is [[https://en.wikipedia.org/wiki/Lights_Out_(game)][Lights Out]], and part 2 is a really interesting generalization of part 1.

Initially I thought I could get away with a memoized search of the full space, but realized this solution would never work.
Perhaps there's a clever way to prune the state space that I did not find which would make this work.

This also required looking some stuff up.
I did figure out that it was a linear system and that this is an ILP problem.
But, I could not remember exactly how to write ILP solver.
Looking it up, I realized there's a ton of solutions here:
1. Z3 is popular
2. Hand rolled Gaussian elimination + a small search at the end
3. "Bifurcation" and a reduction to part1, see [[https://www.reddit.com/r/adventofcode/comments/1pk87hl/2025_day_10_part_2_bifurcate_your_way_to_victory/][reddit]]. I still don't understand this.

Apparently doing elimination, followed by brute force, rather than anything more sophisticated, is a common thing approach in competitive programming.

Even with a rough guide for how to solve the problem, I still had plenty of problem solving to do on my own.
For example, keeping everything in integer needed a bit of work.

I still would like to spend some time exploring this problem.
For example, part 1 could probably be solved using the same techniques as part 2, just in GF(2).
#+END_EXAMPLE
